# Generated by Django 5.0.6 on 2024-06-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('subject', models.CharField(max_length=20, verbose_name='과목')),
                ('role', models.CharField(max_length=10, verbose_name='역할')),
                ('map_image', models.ImageField(upload_to='', verbose_name='약도')),
            ],
        ),
    ]
